import { describe, expect, it } from "vitest";
import { parseManagedDesignSystem } from "../src/generation/existingDesignSystem";
import { createManagedSkillBody } from "../src/renderers/shared";
import { DesignSystemInput } from "../src/types";

const sampleDesign: DesignSystemInput = {
  productName: "typeui.sh",
  brandSummary: "Developer-first UI guidance.",
  visualStyle: "modern and clean",
  typographyScale: "12/14/16/20/24/32",
  colorPalette: "primary, neutral, semantic",
  spacingScale: "4/8/12/16/24/32",
  componentFamilies: ["buttons", "inputs", "cards"],
  accessibilityRequirements: "WCAG 2.2 AA",
  writingTone: "clear and direct",
  doRules: ["use semantic tokens", "preserve hierarchy"],
  dontRules: ["use low contrast", "break spacing rhythm"]
};

describe("parseManagedDesignSystem", () => {
  it("parses managed content generated by renderer", () => {
    const content = createManagedSkillBody("Cursor", sampleDesign);
    expect(parseManagedDesignSystem(content)).toEqual(sampleDesign);
  });

  it("returns null when managed block is missing", () => {
    expect(parseManagedDesignSystem("# Manual only")).toBeNull();
  });
});
