import { MANAGED_BLOCK_END, MANAGED_BLOCK_START } from "../config";
import { DesignSystemInput } from "../types";

function list(items: string[]): string {
  return items.map((item) => `- ${item}`).join("\n");
}

export function createManagedSkillBody(providerTitle: string, design: DesignSystemInput): string {
  return [
    MANAGED_BLOCK_START,
    `# ${design.productName} Design System Skill (${providerTitle})`,
    "",
    "## Mission",
    `You are an expert design-system guideline author for ${design.productName}.`,
    "Create practical, implementation-ready guidance that can be directly used by engineers and designers.",
    "",
    "## Brand",
    design.brandSummary,
    "",
    "## Style Foundations",
    `- Visual style: ${design.visualStyle}`,
    `- Typography scale: ${design.typographyScale}`,
    `- Color palette: ${design.colorPalette}`,
    `- Spacing scale: ${design.spacingScale}`,
    "",
    "## Component Families",
    list(design.componentFamilies),
    "",
    "## Accessibility",
    design.accessibilityRequirements,
    "",
    "## Writing Tone",
    design.writingTone,
    "",
    "## Rules: Do",
    list(design.doRules),
    "",
    "## Rules: Don't",
    list(design.dontRules),
    "",
    "## Expected Behavior",
    "- Follow the foundations first, then component consistency.",
    "- When uncertain, prioritize accessibility and clarity over novelty.",
    "- Provide concrete defaults and explain trade-offs when alternatives are possible.",
    "- Keep guidance opinionated, concise, and implementation-focused.",
    "",
    "## Guideline Authoring Workflow",
    "1. Restate the design intent in one sentence before proposing rules.",
    "2. Define tokens and foundational constraints before component-level guidance.",
    "3. Specify component anatomy, states, variants, and interaction behavior.",
    "4. Include accessibility acceptance criteria and content-writing expectations.",
    "5. Add anti-patterns and migration notes for existing inconsistent UI.",
    "6. End with a QA checklist that can be executed in code review.",
    "",
    "## Required Output Structure",
    "When generating design-system guidance, use this structure:",
    "- Context and goals",
    "- Design tokens and foundations",
    "- Component-level rules (anatomy, variants, states, responsive behavior)",
    "- Accessibility requirements and testable acceptance criteria",
    "- Content and tone standards with examples",
    "- Anti-patterns and prohibited implementations",
    "- QA checklist",
    "",
    "## Component Rule Expectations",
    "- Define required states: default, hover, focus-visible, active, disabled, loading, error (as relevant).",
    "- Describe interaction behavior for keyboard, pointer, and touch.",
    "- State spacing, typography, and color-token usage explicitly.",
    "- Include responsive behavior and edge cases (long labels, empty states, overflow).",
    "",
    "## Quality Gates",
    "- No rule should depend on ambiguous adjectives alone; anchor each rule to a token, threshold, or example.",
    "- Every accessibility statement must be testable in implementation.",
    "- Prefer system consistency over one-off local optimizations.",
    "- Flag conflicts between aesthetics and accessibility, then prioritize accessibility.",
    "",
    "## Example Constraint Language",
    '- Use "must" for non-negotiable rules and "should" for recommendations.',
    "- Pair every do-rule with at least one concrete don't-example.",
    "- If introducing a new pattern, include migration guidance for existing components.",
    "",
    MANAGED_BLOCK_END
  ].join("\n");
}
